version: '3.1'

services:

  db:
    image: postgres
    container_name: triptrick-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_LOCAL_USER}
      POSTGRES_PASSWORD: ${DB_LOCAL_PASSWORD}
      POSTGRES_DB: ${DB_LOCAL_DATABASE}
      # PGDATA: /triptrick-postgres-pg-data
      # PGDATA import backup on create
    # volumes:
    #   - triptrick-pg-data:/triptrick-postgres-pg-data
    ports:
      - ${DB_LOCAL_PORT}:${DB_LOCAL_PORT}


  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080